name: Build and Release APK

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Configurar JDK
        uses: actions/setup-java@v3
        with:
	  distribution: 'temurin'
          java-version: '11'

      - name: Build do APK
        run: ./gradlew assembleRelease

      - name: Criar Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.${{ github.run_number }}
          release_name: Release v1.0.${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload do APK na Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app\build\outputs\apk\release\app-release-unsigned.apk
          asset_name: quilombolaapp.apk
          asset_content_type: application/vnd.android.package-archive
